source 'https://rubygems.org'

gem 'asciidoctor', '~> 1.5.0', '>= 1.5.3'
gem 'asciidoctor-diagram', '~> 1.3.0', '>= 1.3.1' # drawing
gem 'pygments.rb' # syntax highlighter
gem 'slim', '~>2.1' # force latest slim
gem 'thread_safe'

gem 'guard', '~> 2.13.0'

gem 'guard-livereload', '~> 2.5.0', '>= 2.5.1'
gem 'guard-shell', '~> 0.7.1'
gem 'guard-rack', '~> 2.1.0', '>= 2.1.1'
gem 'guard-copy', '~> 0.5.1'

gem 'rack', '~> 1.6', '>= 1.6.4'
